package com.model.pojo;
// Generated 07-21-2022 09:37:50 AM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Visitasweb generated by hbm2java
 */
@Entity
@Table(name = "VISITASWEB", schema = "COOPONEDS")
public class Visitasweb implements java.io.Serializable {

    @Id
    @Column(name = "ID")
    private BigInteger id;
    @Column(name = "USUARIO")
    private String usuario;
    @Column(name = "IDPANTALLA")
    private BigInteger idpantalla;
    @Column(name = "FECHA")
    @Temporal(TemporalType.TIMESTAMP)
    private Date fecha;

    public Visitasweb() {
    }

    public Visitasweb(BigInteger id) {
        this.id = id;
    }

    public Visitasweb(BigInteger id, String usuario, BigInteger idpantalla, Date fecha) {
        this.id = id;
        this.usuario = usuario;
        this.idpantalla = idpantalla;
        this.fecha = fecha;
    }

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public String getUsuario() {
        return this.usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public BigInteger getIdpantalla() {
        return this.idpantalla;
    }

    public void setIdpantalla(BigInteger idpantalla) {
        this.idpantalla = idpantalla;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Override
    public String toString() {
        return "Visitasweb{" + "id=" + id + ", usuario=" + usuario + ", idpantalla=" + idpantalla + ", fecha=" + fecha + '}';
    }
    
    
}
